# Snapshot Downloader Configuration

# URL for the snapshot to download
snapshot_url: "https://example.com/cosmos-snapshot.tar.gz"

# URL for the binary to download
binary_url: "https://example.com/cosmos-binary.tar.gz"

# Relative path to the binary within the workspace directory
# This is used to locate the binary after extraction
binary_relative_path: "bin/gaiad"

# Chain ID for the Cosmos network
chain_id: "cosmoshub-4"

# Moniker (node name) to use when initializing
moniker: "my-cosmos-node"

# Custom home directory for the chain (optional)
# If not specified, defaults to ~/.snapshot-downloader/workspace/home
# chain_home_dir: "/mnt/data/cosmos-home"

# Command to execute after snapshot extraction (optional)
# This will only run if a snapshot is successfully extracted
post_snapshot_command: "echo 'Snapshot extraction completed'"

# Configuration overrides for app.toml
# These values will be merged with the existing app.toml file
app_yaml:
  api:
    enable: true
    swagger: true
  grpc:
    enable: true
  pruning: "custom"
  pruning-keep-recent: "100"
  pruning-interval: "10"

# Configuration overrides for config.toml
# These values will be merged with the existing config.toml file
config_yaml:
  rpc:
    laddr: "tcp://0.0.0.0:26657"
  p2p:
    seeds: "seed1.example.com:26656,seed2.example.com:26656"
    persistent_peers: "peer1.example.com:26656,peer2.example.com:26656" 